const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const { getEnv } = require('../config/env');

const {
  nginx: { confdPath, siteFilesPath, containerName, lanIp }
} = getEnv();

function getSitePath(slug) {
  return path.join(siteFilesPath, slug);
}

function buildLocationBlock(slug) {
  return [
    `# Auto-generated by DropHost backend — deployment: ${slug}`,
    `location /d/${slug}/ {`,
    `  alias ${getSitePath(slug)}/;`,
    '  index index.html;',
    `  try_files $uri $uri/ /d/${slug}/index.html;`,
    '',
    '  # CORS headers for lab environment',
    '  add_header Access-Control-Allow-Origin *;',
    '}',
    ''
  ].join('\n');
}

async function writeConfig(slug) {
  const configText = buildLocationBlock(slug);
  const filePath = path.join(confdPath, `${slug}.conf`);
  await fs.promises.writeFile(filePath, configText);
  return { filePath, configText };
}

function reloadNginx() {
  return new Promise((resolve, reject) => {
    exec(`docker exec ${containerName} nginx -s reload`, (error, stdout, stderr) => {
      if (error) {
        const err = new Error('config written but nginx reload failed — check logs');
        err.statusCode = 500;
        return reject(err);
      }
      resolve();
    });
  });
}

function buildLanUrl(slug) {
  return `http://${lanIp}/d/${slug}/`;
}

async function removeConfigAndFiles(slug) {
  const configPath = path.join(confdPath, `${slug}.conf`);
  const sitePath = getSitePath(slug);

  try {
    await fs.promises.unlink(configPath);
  } catch (err) {
    if (err.code !== 'ENOENT') {
      throw err;
    }
  }

  async function rmDirRecursive(target) {
    try {
      const stats = await fs.promises.lstat(target);
      if (stats.isDirectory()) {
        const entries = await fs.promises.readdir(target);
        await Promise.all(entries.map((entry) => rmDirRecursive(path.join(target, entry))));
        await fs.promises.rmdir(target);
      } else {
        await fs.promises.unlink(target);
      }
    } catch (err) {
      if (err.code !== 'ENOENT') {
        throw err;
      }
    }
  }

  await rmDirRecursive(sitePath);
}

module.exports = {
  writeConfig,
  reloadNginx,
  buildLanUrl,
  removeConfigAndFiles
};

